/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.Cliente;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import repositorios.ClienteRepository;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author vehimar
 */
public class JdCliente extends javax.swing.JDialog {

    private Object clienteBqd;


    ClienteRepository clienteDAO;

    /**
     * Creates new form JDClienteB
     */
    @Autowired
    public JdCliente(java.awt.Dialog parent, boolean modal, ClienteRepository clienteDAO) {
        super(parent, modal);
        initComponents();
//        this.clienteDAO = new NCliente();
        this.clienteDAO = clienteDAO;
        this.setLocationRelativeTo(parent);
        listarClientes(tblListaCliente);
    }

    @Autowired
    JdCliente(JfPrincipal padre, boolean b, ClienteRepository clienteDAO) {
        super(padre, b);
        initComponents();
//        this.clienteDAO = new NCliente();
        this.clienteDAO = clienteDAO;
        this.setLocationRelativeTo(padre);
        listarClientes(tblListaCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PapeleriaDelta.Principal.Cliente");

        tblListaCliente.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "CODIGO", "NOMBRE", "NIT", "TELEFONO"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaCliente);
        tblListaCliente.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblListaCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblListaCliente.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblListaCliente.getColumnModel().getColumn(3).setPreferredWidth(60);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CLIENTE"));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(btnNuevo)
                                .add(26, 26, 26)
                                .add(btnBuscar)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(btnNuevo)
                                        .add(btnBuscar))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                                        .add(layout.createSequentialGroup()
                                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        JdRegistroCliente registroCliente = new JdRegistroCliente(this, true, 0, clienteDAO);
        registroCliente.codigoSiguiente();
        registroCliente.setVisible(true);
        listarClientes(tblListaCliente);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JdRegistroCliente registroCliente = new JdRegistroCliente(this, true, 1, clienteDAO);
        registroCliente.setVisible(true);
        clienteBqd = registroCliente.getClienteBqd();
        if (clienteBqd != null) {
            limpiarTabla(tblListaCliente);
            DefaultTableModel modelo = (DefaultTableModel) tblListaCliente.getModel();
            Cliente clienteAuxiliar = (Cliente) clienteBqd;
            Object[] datos = {clienteAuxiliar.getId(),
                    clienteAuxiliar.getNombre(),
//                    clienteAuxiliar.getNit(),
//                    clienteAuxiliar.getTelefono()
            };
            modelo.addRow(datos);
            tblListaCliente.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(null, "EL CLIENTE NO EXISTE");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaCliente;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla(JTable tabla) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        for (int i = model.getRowCount(); i != 0; i--) {
            model.removeRow(i - 1);
        }
        tabla.setModel(model);
    }

    private void listarClientes(JTable tabla) {
        limpiarTabla(tabla);
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        List<Cliente> lista = clienteDAO.findAll();
        if (lista != null) {
            for (int i = 0; i < lista.size(); i++) {
                Cliente clienteAuxiliar = (Cliente) lista.get(i);
                Object[] datos = {clienteAuxiliar.getId(),
                        clienteAuxiliar.getNombre()
//                        ,
//                    clienteAuxiliar.getNit(),
//                    clienteAuxiliar.getTelefono()
                };
                modelo.addRow(datos);
            }
        }
        tabla.setModel(modelo);
    }
}
