/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.Producto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import repositorios.NProducto;

import javax.swing.*;

/**
 * @author Sinai
 */
public class JdProductoNuevo extends javax.swing.JDialog {

    /**
     * Creates new form JDProductoNuevo
     */
    @Autowired
    public JdProductoNuevo(java.awt.Dialog parent, boolean modal, NProducto nProducto) {
        super(parent, modal);
        this.nProducto = nProducto;
        initComponents();
        this.setLocationRelativeTo(parent);
        agregar = true;
//        nProducto = new NProducto();

        try {
            String codigo = nProducto.codigoSiguiente();
            txtCodigo.setText(codigo);
        } catch (NullPointerException npe) {
            txtCodigo.setText("1");
        }
    }

    /**
     * Creates new form JDProductoNuevo
     */
    @Autowired
    public JdProductoNuevo(java.awt.Dialog parent, boolean modal, String[] datos, NProducto nProducto) {
        super(parent, modal);
        this.nProducto = nProducto;
        initComponents();
        lblTitulo.setText("Modificar Producto");
        agregar = false;
        this.setLocationRelativeTo(parent);
//        nProducto = new NProducto();
        mostrarDatos(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProducto = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecioReferencia = new javax.swing.JLabel();
        lblObservacion = new javax.swing.JLabel();
        txtPrecioReferencia = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelProducto.setBackground(new java.awt.Color(204, 204, 204));

        lblCodigo.setText("Código");

        txtCodigo.setEnabled(false);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        lblNombre.setText("*Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblPrecioReferencia.setText("Precio Referencia");

        lblObservacion.setText("*Marca");

        txtPrecioReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioReferenciaKeyTyped(evt);
            }
        });

        txtObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionActionPerformed(evt);
            }
        });
        txtObservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacionKeyTyped(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("Nuevo Producto");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
                jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProductoLayout.createSequentialGroup()
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelProductoLayout.createSequentialGroup()
                                                .addGap(140, 140, 140)
                                                .addComponent(lblTitulo))
                                        .addGroup(jPanelProductoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblCodigo)
                                                        .addComponent(lblNombre)
                                                        .addComponent(lblPrecioReferencia)
                                                        .addComponent(lblObservacion))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtPrecioReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelProductoLayout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanelProductoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{txtNombre, txtObservacion});

        jPanelProductoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{txtCodigo, txtPrecioReferencia});

        jPanelProductoLayout.setVerticalGroup(
                jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProductoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitulo)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCodigo)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNombre)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPrecioReferencia)
                                        .addComponent(txtPrecioReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblObservacion)
                                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char car = evt.getKeyChar();
        //        Si quisieramos que la longitud maxima fuera 8
        //        if(txtNumerico.getText().length()>=8) evt.consume();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPrecioReferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioReferenciaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioReferenciaKeyTyped

    private void txtObservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionKeyTyped

    private void txtObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (agregar) {
            if (agregarProducto()) {
                this.dispose();
            }
        } else {
            if (modificarProducto()) {
                this.dispose();
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private boolean esValidoLaInformacionDeEntrada(String nombre, String precioReferencia, String marca) {
        boolean verificado = false;

        if (!nombre.isEmpty()) {
            if (!marca.isEmpty()) {
                if (!precioReferencia.isEmpty()) {
                    if (esNumeroDecimal(precioReferencia)) {
                        verificado = true;
                    }
                } else {
                    verificado = true;
                }
            } else {
                JOptionPane.showMessageDialog(null, "la Marca no puede ser vacia");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El nombre del producto no puede ser vacio");
        }


        return verificado;
    }

    /**
     * este metodo verifica si un numero es decimal
     *
     * @param numero
     * @return boolean
     */
    private boolean esNumeroDecimal(String numero) {
        boolean verificado = true;
        try {
            Float.parseFloat(numero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio referencia es invalido");
            verificado = false;
        }
        return verificado;
    }

    /**
     * este metodo verifica si un numero es decimal
     *
     * @param numero
     * @return boolean
     */
    private boolean esNumero(String numero) {
        boolean verificado = true;
        try {
            Integer.valueOf(numero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio referencia es invalido");
            verificado = false;
        }
        return verificado;
    }

    /**
     *
     */
    private boolean agregarProducto() {
        boolean resultado = false;

        String nombre = txtNombre.getText().trim();
        String precioReferencia = txtPrecioReferencia.getText().trim();
        String observacion = txtObservacion.getText().trim();
        float precioReferenciaConvertido = 0;
        boolean esValido = esValidoLaInformacionDeEntrada(nombre, precioReferencia, observacion);
        boolean esUnico = true;
        //nProducto.esProductoNuevo(nombre, observacion);
        if (esValido && esUnico) {

            if (!precioReferencia.isEmpty()) {
                precioReferenciaConvertido = Float.parseFloat(precioReferencia);
            }

            nProducto.save(new Producto(nombre, 0)); //observacion, precioReferenciaConvertido
            JOptionPane.showMessageDialog(null, "El producto se ha agregado correctamente");
            resultado = true;
        }

        return resultado;
    }

    private void mostrarDatos(String[] datos) {
        txtCodigo.setText(datos[0]);
        txtNombre.setText(datos[2]);
        txtPrecioReferencia.setText(datos[3]);
        txtObservacion.setText(datos[4]);
    }

    private boolean modificarProducto() {
        boolean resultado = false;

        String nombre = txtNombre.getText().trim();
        String precioReferencia = txtPrecioReferencia.getText().trim();
        String observacion = txtObservacion.getText().trim();

        boolean esValido = esValidoLaInformacionDeEntrada(nombre, precioReferencia, observacion);

        if (esValido) {
            float precioReferenciaConvertido = Float.parseFloat(precioReferencia);
            int codigo = Integer.valueOf(txtCodigo.getText());
            int stock = nProducto.stockDisponible(codigo);
            nProducto.save(new Producto(codigo, nombre, stock, null, null)); //observacion, precioReferenciaConvertido
            JOptionPane.showMessageDialog(null, "El producto se ha modificado correctamente");
            resultado = true;
        }

        return resultado;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblPrecioReferencia;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtPrecioReferencia;
    // End of variables declaration//GEN-END:variables
    private final NProducto nProducto;
    private boolean agregar;
}
