/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.Cliente;
import entidades.Venta;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import repositorios.ClienteRepository;
import repositorios.NDetalleVenta;
import repositorios.NProducto;
import repositorios.NVenta;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * @author Fredy
 */
public class JdVentaNuevo extends javax.swing.JDialog {

    /**
     * Creates new form JdVentaNuevo
     */
    private List<Venta> listVenta;
    private Cliente cliente;

    private final NVenta nventa;
    private final NDetalleVenta ndetalleventa;
    private final ClienteRepository ncliente;
    private final NProducto nproducto;


    public JdVentaNuevo(java.awt.Dialog parent, boolean modal, NVenta nventa, ClienteRepository ncliente, NDetalleVenta ndetalleventa, NProducto nproducto) {
        super(parent, modal);
        this.nventa = nventa;
        this.ncliente = ncliente;
        this.ndetalleventa = ndetalleventa;
        this.nproducto = nproducto;
        initComponents();

//        nventa = new NVenta();
        listVenta = new ArrayList<Venta>();
        cliente = new Cliente();
//        ncliente = new NCliente();
        listVenta = nventa.findAll();
        listarVenta(tblVentas);
        this.setLocationRelativeTo(null);

    }

    @Autowired
    JdVentaNuevo(JfPrincipal padre, boolean b, NVenta nventa, ClienteRepository ncliente, NDetalleVenta ndetalleventa, NProducto nproducto) {
        super(padre, b);
        this.nventa = nventa;
        this.ncliente = ncliente;
        this.ndetalleventa = ndetalleventa;
        this.nproducto = nproducto;
        initComponents();

//        nventa = new NVenta();
        listVenta = new ArrayList<Venta>();
        cliente = new Cliente();
//        ncliente = new NCliente();
        try {
            listVenta = nventa.findAll();
        }catch (NullPointerException npe){
            listVenta = new ArrayList<>();
        }
        listarVenta(tblVentas);
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setText("VENTAS");

        btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String[]{
                        "CODIGO VENTA", "FECHA", "NOMBRE"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblVentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblVentasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addComponent(lblTitulo)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblTitulo)
                                .addGap(28, 28, 28)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMousePressed
        int x = tblVentas.getSelectedRow();
        int codigo = (Integer) (tblVentas.getModel().getValueAt(x, 0));
        Date fecha = (Date) (tblVentas.getModel().getValueAt(x, 1));
        String nombre = (String) (tblVentas.getModel().getValueAt(x, 2));

        JdVentaDetalle jdventadetalle = new JdVentaDetalle(this, true, ndetalleventa, nproducto);
        jdventadetalle.setJdFormDetalle(codigo);
        jdventadetalle.setDatosform(fecha, nombre);
        jdventadetalle.setVisible(true);

    }//GEN-LAST:event_tblVentasMousePressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.dispose();
        JdVenta jdVenta = new JdVenta(null, true, nproducto,nventa,ndetalleventa,ncliente);
        jdVenta.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla(JTable tabla) {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        for (int i = model.getRowCount(); i != 0; i--) {
            model.removeRow(i - 1);
        }
        tabla.setModel(model);
    }

    private void listarVenta(JTable tabla) {
        limpiarTabla(tabla);
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

        if (listVenta != null) {
            for (int i = 0; i < listVenta.size(); i++) {
                Venta venta = (Venta) listVenta.get(i);
                cliente = (Cliente) ncliente.findById(venta.getCliente().getId()).orElse(null);
                Object[] datos = {
                        venta.getId(),
                        venta.getFecha(),
                        cliente.getNombre()
                };
                modelo.addRow(datos);
            }
        }
        tabla.setModel(modelo);
    }
}
