/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import repositorios.*;

import java.awt.*;

/**
 * @author Fredy
 */
@Component
public class JfPrincipal extends javax.swing.JFrame {

    @Autowired
    private ClienteRepository clienteDAO;
    @Autowired
    private NCompra nCompra;
    @Autowired
    private NVenta nVenta;
    @Autowired
    private NDetalleVenta ndetalleventa;
    @Autowired
    private ClienteRepository nCliente;
    @Autowired
    private NProducto nProducto;

    /**
     * Creates new form JfPrincipal
     */
    public JfPrincipal() {
        initComponents();
        centrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProducto = new javax.swing.JButton();
        bntCliente = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("PEPELEIRA");
        jPanel1.add(lblTitulo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rf.png"))); // NOI18N
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductoMousePressed(evt);
            }
        });

        bntCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rrhh.png"))); // NOI18N
        bntCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bntClienteMousePressed(evt);
            }
        });

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opc.png"))); // NOI18N
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCompraMousePressed(evt);
            }
        });

        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opv.png"))); // NOI18N
        btnVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentaMousePressed(evt);
            }
        });
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnProducto)
                                                .addGap(18, 18, 18)
                                                .addComponent(bntCliente))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(btnCompra)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnVenta)))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bntCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnVenta)
                                        .addComponent(btnCompra))
                                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed

    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaMousePressed
        // TODO add your handling code here:
        JdVentaNuevo jdVentaNuevo = new JdVentaNuevo(this, true, nVenta, nCliente, ndetalleventa, nProducto);
        jdVentaNuevo.setVisible(true);
    }//GEN-LAST:event_btnVentaMousePressed

    private void btnCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMousePressed

        JdCompra compra = new JdCompra(this, true, nCompra, nProducto);
        compra.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompraMousePressed

    private void bntClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntClienteMousePressed

        JdCliente cliente = new JdCliente(this, true, clienteDAO);
        cliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bntClienteMousePressed

    private void btnProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMousePressed
        // TODO add your handling code here:

        JdProducto jdProducto = new JdProducto(this, true, nProducto);
        jdProducto.setVisible(true);
    }//GEN-LAST:event_btnProductoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCliente;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    private void centrar() {
        setLocationRelativeTo(null);
    }
}
