package entidades;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
@Entity//(name = "cliente")
@NoArgsConstructor
@Getter
@Setter
public class Cliente implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

//    @Column(name = "nombre_cliente", length = 100, nullable = false)
    private String nombre;
    @OneToMany
    private Set<Venta> ventas = new HashSet<>(0);

    public Cliente(String nombre) {
        this.nombre = nombre;
    }

    public Cliente(String nombre, Set<Venta> ventas) {
        this.nombre = nombre;
        this.ventas = ventas;
    }

}


