package entidades;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
@Entity
@Getter
@Setter
public class Compra implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(length = 10, nullable = false)
    private Date fecha;
    @Column(length = 100)
    private String nombreProveedor;
    @OneToMany
    private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

    public Compra() {
    }


    public Compra(Date fecha) {
        this.fecha = fecha;
    }

    public Compra(Date fecha, String nombreProveedor, Set<Detallecompra> detallecompras) {
        this.fecha = fecha;
        this.nombreProveedor = nombreProveedor;
        this.detallecompras = detallecompras;
    }

}


