package entidades;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

/**
 * Detalleventa generated by hbm2java
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Detalleventa implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(nullable = false)
    private Venta venta;
//    @ManyToOne
    @Column(nullable = false)
    private Producto producto;
    @Column(nullable = false)
    private int preciounidad;
    @Column(nullable = false)
    private int cantidad;

    public Detalleventa(Integer id, Venta venta, Producto producto, int preciounidad, int cantidad) {
        this.id = id;
        this.venta = venta;
        this.producto = producto;
        this.preciounidad = preciounidad;
        this.cantidad = cantidad;
    }
}


