package entidades;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import lombok.*;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Producto implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    @Column(length = 100, nullable = false)
    private String nombre;
    @Column(nullable = false)
    private int stock;
    @OneToMany//(mappedBy = "idproducto")
    private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);
    @OneToMany
    private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);


    public Producto(String nombre, int stock) {
        this.nombre = nombre;
        this.stock = stock;
    }

    @Override
    public String toString() {
        return nombre + '-' + stock;
    }
}


