package entidades;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
@Entity
@Setter
@Getter
public class Venta implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @ManyToOne
    private Cliente cliente;
    private Date fecha;
    @OneToMany
    private Set<Detalleventa> detalleventas = new HashSet<>(0);

    public Venta() {
    }


    public Venta(Date fecha) {
        this.fecha = fecha;
    }

    public Venta(Cliente cliente, Date fecha, Set<Detalleventa> detalleventas) {
        this.cliente = cliente;
        this.fecha = fecha;
        this.detalleventas = detalleventas;
    }
}


